all:
	Rscript -e 'rmarkdown::render("Error-Correction.Rmd")'


pdf:
	Rscript -e 'rmarkdown::render("Error-Correction.Rmd", output_format="pdf_document")'


clean:
	rm Error-Correction.pdf Error-Correction.html
