---
title: Finance 6470 - Derivatives Markets
subtitle: Chapter 1 - Introduction to Derivatives
author: Tyler J. Brough
institute: Department of Finance and Economics 
titlegraphic: ./images/vertical-logo-blue.png
fontsize: 10pt
output:
 beamer_presentation:
    template: ./beamer-template.tex
    keep_tex: true
# toc: true
    slide_level: 2
 ioslides_presentation:
    smaller: true
#    logo: ~/Dropbox/teaching/clemson-paw-transparent.png
make149: true
---

<style>
slides > slide.backdrop {
  background: white;
  border-bottom: 0px;
  box-shadow: 0 0 0;
}


slides > slide {
  font-family: 'Open Sans', Helvetica, Arial, sans-serif;
  border-bottom: 3px solid  #F66733;
  box-shadow:  0 3px 0 #00488D;

}

.title-slide hgroup h1 {
  color: #00488D;
}



h2 {

  color: #00488D;
}

slides > slide.dark {
  background: #00488D !important;
  border-bottom: 0;
  box-shadow: 0 0 0;
}

.segue h2 {
  color: white;
}

slides > slide.title-slide {
  border-bottom: 0;
  box-shadow: 0 0 0;
}

ol, ul {

padding-bottom: 10px;

}

</style>


# Chapter 1: Introduction to Derivatives

## What is a Derivative? 

* __Definition:__ a financial instrument that has a value determined by the price of something else


* An agreement where you pay $\$1$ if the price of corn is greater than $\$3$ and receive $\$1$ if the
  price of corn is less than $\$1$ is a derivative
	- This contract can be used to speculate on the price of corn or it can be used to reduce risk. It
	  is not the contract itself, but how it used, and who uses it, that determines whether or not it is
	  risk-reducing.


## An Overview of Financial Markets

The trading of a financial asset involves at least four discrete steps:

* A buyer and a sellter must locate one another and agree on a price

* The trade must be _cleared_ (the obligations of each party are specified)

* The trade must be _settled_ (the buyer and the seller must deliver the cash
  or securities necessary to satisfy their obligations in the required period
  of time)

* Ownership records are updated 

\vspace{3mm}

___NB:___ notice that well-defined property rights are an assumption of 
properly functioning capital markets.


## An Overview of Financial Markets (Continued)

* Much trading of financial claims takes place on organized exchanges. In the past, the exchange
  was solely a physical location where traders would buy and sell. Such in-person venues have 
  largely been replaced by electronic networks that provide a virtual trading venue. 

* After a trade has taken place, a __clearinghouse__ matches the buyers and sellers, keeping
  track of their obligations and payments. To facilitate these payments and to help manage 
  credit risk, a derivatives clearinghouse typically imposes itself in the transaction, becoming
  the buyer to all sellers and the seller to all buyers. 


## An Overview of Financial Markets (Continued)

* It is possible for large traders to trade many financial claims directly with a dealer bypassing
  organized exchanges. Such trading is said to occur in the __over-the-counter__ (OTC) market

* Exchange activity is public and highly regulated

* OTC trading is not easy to observe or measure and is generally less regulated

* For many categories of financial claims, the value of OTC trading is greater than the value traded
  on exchanges.


## An Overview of Financial Markets (Continued)

There are at least four different measures of a market and its activity

*  __Trading volume__. This measure counts the number of financial claims that change hands

* __Market value__. The market value is the sum of the market value of the claims that _could_ 
  be traded, without regard to whether they have traded


* __Notional value__. Notional value measure the _scale_ of a position, usually with reference
  to some underlying asset


* __Open Interest__. Open interest measures the total number of contracts for which counterparties
  have a future obligation to perform






